### ISSUE TITLE
delete button not working

### ISSUE THREAD

**Issue by aimeejulia** [aimeejulia/dlist#3]
current delete button for individual tasks is not working, something is wrong with the js code for this

**Comment by ZPPD** [comment]
@aimeejulia Can I also try implementing the functionality of the button? :)

**Comment by aimeejulia** [comment]
I think I managed to fix the assignee issue also, you should have an invite to be added as a contributor on the project this will add your name to the repo as contributor and allow you to assign tasks to yourself

**Comment by aimeejulia** [comment]
looks great :-)
