### ISSUE TITLE
change the current delete button to match the page style

### ISSUE THREAD

**Issue by aimeejulia** [aimeejulia/dlist#7]
add minus icon (fa) for delete near added task list item

**Comment by ZPPD** [comment]
Hey @aimeejulia, I can take on this issue. Is the UI part all you need, what about functionality?

**Comment by aimeejulia** [comment]
only the UI as the functionality is tagged on a separate issue

**Comment by aimeejulia** [comment]
I can't seem to updated the assignee to you though, do you have access to do that from your side? and also move the task on the project board from to do to in progress?

**Comment by ZPPD** [comment]
I can't seem to change the assignee or the project board either.

**Comment by ZPPD** [comment]
![screenshot](https://user-images.githubusercontent.com/38818964/45708909-936d6d00-bb50-11e8-98ce-7c56b635de88.png)
How is this looking?
